apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-filestore-pv
  namespace: slurm
spec:
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeAttributes:
      ip: <your-filestore-private-ip>
      volume: nfsshare
    volumeHandle: modeInstance/asia-southeast1-a/<your-filestore-instance-id>/nfsshare
  accessModes:
    - ReadWriteMany
  mountOptions:
    - implicit-dirs
    - metadata-cache:ttl-secs:-1
    - metadata-cache:stat-cache-max-size-mb:-1
    - metadata-cache:type-cache-max-size-mb:-1
    - file-cache:max-size-mb:-1
    - file-cache:cache-file-for-range-read:true
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-filestore-pvc
  namespace: slurm
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: slurm-filestore-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
