apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-training-pv
  namespace: slurm
spec:
  volumeMode: Filesystem
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <your-training-gcs-name>
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
  accessModes:
    - ReadWriteMany
  mountOptions:
    - implicit-dirs
    - metadata-cache:ttl-secs:-1
    - metadata-cache:stat-cache-max-size-mb:-1
    - metadata-cache:type-cache-max-size-mb:-1
    - file-cache:max-size-mb:-1
    - file-cache:cache-file-for-range-read:true
  capacity:
    storage: 1000000Gi
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-training-pvc
  namespace: slurm
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: slurm-training-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000000Gi
